### PR TITLE
Use a more pythonic way

### PR DESCRIPTION
**Pull request by ebrahimraeyat**

### CODE REVIEW

**Comment by lcpt** [comment]
Thanks, Ebrahim.

Have you checked your code against the verification tests?

**Comment by ebrahimraeyat** [comment]
No, I will try to compile xc and test it!

**Comment by lcpt** [comment]
OK, thanks!

**Comment by lcpt** [comment]
Any news about this?

**Comment by ebrahimraeyat** [comment]
Thanks @lcpt . I recompiled it today and run tests. some tests fails, I don't think related to this changes:

```bash
test test_shell_mitc4_28.py: ok.
test test_shell_mitc9_01.py: ok.
ERROR:root:test_shell_mitc9_02.py ERROR.
ratio1=  nan
RN1=  nan RN2=  nan RN3=  nan RN4=  nan
test test_shell_mitc9_03.py: ok.
```

```bash
test modal_analysis_test_04.py: ok.
test modal_analysis_test_05.py: ok.
XC::SolutionStrategy::alloc_system_of_equations; system of equations: 'spectra_eigen_soe' unknown.
ERROR:root:FrequencyAnalysis.sysOfEqnSetup; could not get a system of equations of type: 'spectra_eigen_soe' probably is not a valid type or it is not implemented in your system.
     Linear buckling analysis tests.
test linear_buckling_column01.py: ok.
```

```bash
test test_paving_02.py: ok.
test test_paving_03.py: ok.
ERROR:root:test_paving_04.py ERROR.
test test_paving_07.py: ok.
test test_gmsh_01.py: ok.
```
```bash
test test_fiber_section_shear3d_01.py: ok.
ERROR:root:test_fiber_section_shear3d_02.py ERROR.
test test_fiber_section_prop.py: ok.
```

```bash
test: test_embankment_02.py: ok.
ERROR:root:test: test_embankment_03.py ERROR.
test: test_embankment_04.py: ok.
```

```bash
test test_simple_beam_oscillation.py: ok.
   Earth retaining structures...
ERROR:root:retaining_wall_test_01.py ERROR.
test retaining_wall_test_02.py: ok.
```

**Comment by ebrahimraeyat** [comment]
Hello @lcpt , Any news about this? Is it require something else?

**Review by lcpt — APPROVED** [review]
I've been hesitant because the modifications introduced in `getPathPolygon` are not checked by any of the existing verification tests. I will write a new test to make sure that all continues to work as expected.

**Comment by lcpt** [comment]
> Thanks @lcpt . I recompiled it today and run tests. some tests fails, I don't think related to this changes:
> 
> ```shell
> test test_shell_mitc4_28.py: ok.
> test test_shell_mitc9_01.py: ok.
> ERROR:root:test_shell_mitc9_02.py ERROR.
> ratio1=  nan
> RN1=  nan RN2=  nan RN3=  nan RN4=  nan
> test test_shell_mitc9_03.py: ok.
> ```
> 
> ```shell
> test modal_analysis_test_04.py: ok.
> test modal_analysis_test_05.py: ok.
> XC::SolutionStrategy::alloc_system_of_equations; system of equations: 'spectra_eigen_soe' unknown.
> ERROR:root:FrequencyAnalysis.sysOfEqnSetup; could not get a system of equations of type: 'spectra_eigen_soe' probably is not a valid type or it is not implemented in your system.
>      Linear buckling analysis tests.
> test linear_buckling_column01.py: ok.
> ```
> 
> ```shell
> test test_paving_02.py: ok.
> test test_paving_03.py: ok.
> ERROR:root:test_paving_04.py ERROR.
> test test_paving_07.py: ok.
> test test_gmsh_01.py: ok.
> ```
> 
> ```shell
> test test_fiber_section_shear3d_01.py: ok.
> ERROR:root:test_fiber_section_shear3d_02.py ERROR.
> test test_fiber_section_prop.py: ok.
> ```
> 
> ```shell
> test: test_embankment_02.py: ok.
> ERROR:root:test: test_embankment_03.py ERROR.
> test: test_embankment_04.py: ok.
> ```
> 
> ```shell
> test test_simple_beam_oscillation.py: ok.
>    Earth retaining structures...
> ERROR:root:retaining_wall_test_01.py ERROR.
> test retaining_wall_test_02.py: ok.
> ```

Those errors are not related with the changes of this PR but, they are strange. The only known error is that of program  `test_shell_mitc9_02.py` (which is an intermittent error), in the rest of the cases no errors should occur. Are you using a 32-bit platform?

**Comment by ebrahimraeyat** [comment]
I have ubuntu wsl system on windows:

```bash
root@DESKTOP-7AJHP3M:~# uname -p
x86_64
```

**Comment by lcpt** [comment]
It's strange. Unfortunately, at this moment, I have no access to a WSL machine. I'll take a look when I have the opportunity.

**Pull request merged**
