### PR TITLE
Fix 'testing eqality to None' python issues

### PR DESCRIPTION
**Pull request by luzpaz**
"When you compare an object to None, use is rather than ==. None is a singleton object, comparing using == invokes the __eq__ method on the object in question, which may be slower than identity comparison. Comparing to None using the is operator is also easier for other programmers to read."

### CODE REVIEW

**Comment by lcpt** [comment]
I didn't know. Thank you!

**Comment by luzpaz** [comment]
I learned it via LGTM https://lgtm.com/logs/a5377a114ddd54680fb05f702236df1a10f5d5d6/lang:python

**Comment by lcpt** [comment]
Curious. I didn't know this "compiling robot". Thanks!

**Comment by luzpaz** [comment]
https://lgtm.com/projects/g/xcfem/xc/?mode=tree

**Comment by lcpt** [comment]
Wow. Impressive! Thanks a lot. I didn't know we have so many little bugs everywhere.

**Pull request merged**
